---
title: "2. Cumulative incidence plot"
author: "SeuljiMoon"
date: "2023-08-28"
output: html_document
---

### install.packages
```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
if(!require("ggplot2")) install.packages("ggplot2")
if(!require("tableone")) install.packages("tableone")
if(!require("data.table")) install.packages("data.table")
if(!require("ggpubr")) install.packages("ggpubr")
if(!require("gridExtra")) install.packages("gridExtra")
if(!require("cobalt")) install.packages("cobalt")
if(!require("MatchIt")) install.packages("MatchIt")
if(!require("magrittr")) install.packages("magrittr")
if(!require("moonBook")) install.packages("moonBook")
if(!require("dplyr")) install.packages("dplyr")
if(!require("parallel")) install.packages("parallel")
if(!require("survival")) install.packages("survival")
if(!require("cmprsk")) install.packages("cmprsk")
if(!require("lubridate")) install.packages("lubridate")
if(!require("survplot")) install.packages("survplot")
     
library(data.table); library(dplyr);
library(magrittr);library(parallel);library(ggplot2);library(tableone)
library(survival);library(survminer);library(cmprsk)
library(lubridate)
library(survplot)
library(moonBook)
```


### Data manipulation
```{r}
frac_entire<-fread("~\\fracture_match13_entire_0804.csv") # 1:3 매칭 데이터셋

# incidence_time 
frac_entire<- frac_entire %>% 
  mutate(death = ifelse(is.na(DTH_ASSMD_DT),0,1),
         end_date = "20201231",
         day_frac2=ymd(frac_date),
         day_index2=ymd(indexdate),
         day_end2=ymd(end_date),
         day_death2=ymd(DTH_ASSMD_DT)
         
  ) %>%
  mutate(event2=ifelse(frac_yes==0 & death==0, 0,
                       ifelse(frac_yes==0 & death==1,2,
                              ifelse(frac_yes==1 & death==0,1,
                                     ifelse(frac_yes==1 & death==1 & (day_frac2<=day_death2),1,
                                            ifelse(frac_yes==1 & death==1 & (day_frac2>day_death2),2,0)))))) %>%
  mutate(futime=ifelse(event2==0,difftime(as.Date(day_end2,"%Y%m%d"),
                                          as.Date(day_index2,"%Y%m%d"),units="days"),
                       ifelse(event2==1,difftime(as.Date(day_frac2,"%Y%m%d"),
                                                 as.Date(day_index2,"%Y%m%d"),units="days"),
                              difftime(as.Date(day_death2,"%Y%m%d"),
                                       as.Date(day_index2,"%Y%m%d"),units="days")))) %>% 
  mutate(surv_years = futime/365.25) %>%
  mutate(event_spine=ifelse(is.na(sub) & death==0, 0,
                            ifelse(is.na(sub) & death==1,2,
                                   ifelse(sub==1 & death==0,1,
                                          ifelse(sub==1 & death==1 & (day_frac2<=day_death2),1,
                                                 ifelse(sub==1 & death==1 & (day_frac2>day_death2),2,0)))))) %>%
  mutate(event_hip=ifelse(is.na(sub) & death==0, 0,
                          ifelse(is.na(sub) & death==1,2,
                                 ifelse(sub==2 & death==0,1,
                                        ifelse(sub==2 & death==1 & (day_frac2<=day_death2),1,
                                               ifelse(sub==2 & death==1 & (day_frac2>day_death2),2,0)))))) %>% 
  mutate(event_upper=ifelse(is.na(sub) & death==0, 0,
                            ifelse(is.na(sub) & death==1,2,
                                   ifelse(sub==3 & death==0,1,
                                          ifelse(sub==3 & death==1 & (day_frac2<=day_death2),1,
                                                 ifelse(sub==3 & death==1 & (day_frac2>day_death2),2,0)))))) %>% 
  mutate(death_time = ifelse(death==0, difftime(as.Date(day_end2,"%Y%m%d"),
                                                as.Date(day_index2,"%Y%m%d"),units="days"),
                             difftime(as.Date(day_death2,"%Y%m%d"),
                                      as.Date(day_index2,"%Y%m%d"),units="days"))) %>% 
  mutate(death_years = death_time/365.25) %>% 
  mutate(spine_yes2 = ifelse(sub==1,1,0),
         hip_yes2 = ifelse(sub==2,1,0),
         upper_yes2 = ifelse(sub==3,1,0),
         multi_yes2 = ifelse(sub==4,1,0)) %>% 
  filter(is.na(sub) | sub ==1 | sub==2 | sub==3)

frac_entire$event3<-factor(frac_entire$event2,levels=c(0,1,2))
frac_entire$group <-factor(ifelse(frac_entire$c90_yn==0,2,1),levels=c(1,2)) # 1: case, 2:control
frac_entire$event3_spine<-factor(frac_entire$event_spine,levels=c(0,1,2))
frac_entire$event3_hip<-factor(frac_entire$event_hip,levels=c(0,1,2))
frac_entire$event3_upper<-factor(frac_entire$event_upper,levels=c(0,1,2))

frac_entire <- as.data.table(frac_entire)
```


### Cumulative incidence plot 
The visualization of the cumulative incidence plot was achieved using the `jskm` package.
**status variable**: 0 - censoring / 1 - event / 2 - competing risk
```{r}
fit_entire <- survfit(Surv(surv_years,event3)~group, data=frac_entire)

###y-axis 100, cut 8
a<-jskm(fit_entire, ci = T, mark = F,ystrataname = "Group", surv.scale = "percent", table = T,pval =T,showpercent=T,
        legendposition=c(0.85,0.85),xlims = c(0,8),main="Fracture - Entire cohort (cut 8 year)")

editable_graph <- dml(ggobj=a)
doc<-read_pptx()
doc<-add_slide(doc)
doc<-ph_with(x=doc, editable_graph,
             location=ph_location_type(type="body"))
print(doc, target="~\\0804_Fracture_jskm_plot.pptx")

##y-axis 30, cut 8
a<-jskm(fit_entire, ci = T, mark = F,ystrataname = "Group", surv.scale = "percent", table = T,pval =T,showpercent=T,
        legendposition=c(0.85,0.85),ylims = c(0,0.3),xlims = c(0,8),main="Fracture - Entire cohort (cut 8 year)")
editable_graph <- dml(ggobj=a)
doc<-add_slide(doc)
doc<-ph_with(x=doc, editable_graph,
             location=ph_location_type(type="body"))
print(doc, target="~\\0804_Fracture_jskm_plot.pptx")

######## 1-year cut #########
frac_entire_1year <- frac_entire[frac_entire$surv_years >= 1,]
fit_entire1 <- survfit(Surv(surv_years,event3)~group, data=frac_entire_1year)

###y-axis 100, cut 8
a<-jskm(fit_entire1, ci = T, mark = F,ystrataname = "Group", surv.scale = "percent", table = T,pval =T,showpercent=T,
        legendposition=c(0.85,0.85),xlims = c(1,8),main="Fracture - cut landmark 1-year (cut 8 year)")

editable_graph <- dml(ggobj=a)
doc<-add_slide(doc)
doc<-ph_with(x=doc, editable_graph,
             location=ph_location_type(type="body"))
print(doc, target="~\\0804_Fracture_jskm_plot.pptx")

##y-axis 30, cut 8
a<-jskm(fit_entire1, ci = T, mark = F,ystrataname = "Group", surv.scale = "percent", table = T,pval =T,showpercent=T,
        legendposition=c(0.85,0.85),ylims = c(0,0.3),xlims = c(1,8),main="Fracture - cut landmark 1-year (cut 8 year)")
editable_graph <- dml(ggobj=a)
doc<-add_slide(doc)
doc<-ph_with(x=doc, editable_graph,
             location=ph_location_type(type="body"))
print(doc, target="~\\0804_Fracture_jskm_plot.pptx")


```


### Cumulative incidence plot - fracture subtypes

```{r}
for (i in c("spine","hip","upper")) { 


        fit_entire <- survfit(Surv(surv_years,get(paste0("event3_",i)))~group, data=frac_entire)

        a<-jskm(fit_entire, ci = T, mark = F,ystrataname = "Group", surv.scale = "percent", table = T,pval =T,showpercent=T,
                legendposition=c(0.85,0.85),ylims = c(0,0.1),xlims = c(0,8),main= paste0("Fracture - subgroup : ", i))
        editable_graph <- dml(ggobj=a)
        doc<-add_slide(doc)
        doc<-ph_with(x=doc, editable_graph,
                     location=ph_location_type(type="body"))
        print(doc, target="~\\0804_Fracture_jskm_plot.pptx")

        # 1-year landmark
        frac_entire_1year <- frac_entire[frac_entire$surv_years >= 1,]
        fit_entire <- survfit(Surv(surv_years,get(paste0("event3_",i)))~group, data=frac_entire_1year)

        a<-jskm(fit_entire, ci = T, mark = F,ystrataname = "Group", surv.scale = "percent", table = T,pval =T,showpercent=T,
                legendposition=c(0.85,0.85),ylims = c(0,0.1),xlims = c(1,8),main= paste0("Fracture - subgroup : ", i,"_1 year landmark"))
        editable_graph <- dml(ggobj=a)
        doc<-add_slide(doc)
        doc<-ph_with(x=doc, editable_graph,
                     location=ph_location_type(type="body"))
        print(doc, target="~\\0804_Fracture_jskm_plot.pptx")
        
}

```






